config/routes.rb
Rails.application.routes.draw do
  resources :challenges
  root to: 'pages#home'
  get '/learn-now' => "pages#learn"
  get '/learn' => "users#edit"
  get '/challenge' => "pages#challenges"
  # devise_for :users
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users do
  	resources :apps
  end 	

end

app/models/app.rb
class App < ActiveRecord::Base
  belongs_to :user
end

app/models/challenge.rb
class Challenge < ActiveRecord::Base
	validates :title, presence: true 
	validates :body, presence: true 
	validates :prize, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :apps	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController

  def create 
  	@user = App.find(params[:user_id])
  	@user_app =@user.apps.create(apps_params)
  	flash[:notice] = "Application has been created"
  	redirect_to @user 
  end 	

  def destroy 
  	@user = App.find(params[:user_id])
  	@user_app =@user.apps.destroy
  	flash[:notice] = "Application has been deleted"
  	redirect_to @user 
  end 

  private 

  def apps_params 
  	params.require(:app).permit(:my_type)
  end 	
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  before_action :set_challenge, only: [:show, :edit, :update, :destroy]

  # GET /challenges
  # GET /challenges.json
  def index
    @challenges = Challenge.all
  end

  # GET /challenges/1
  # GET /challenges/1.json
  def show
  end

  # GET /challenges/new
  def new
    @challenge = Challenge.new
  end

  # GET /challenges/1/edit
  def edit
  end

  # POST /challenges
  # POST /challenges.json
  def create
    @challenge = Challenge.new(challenge_params)

    respond_to do |format|
      if @challenge.save
        format.html { redirect_to @challenge, notice: 'Challenge was successfully created.' }
        format.json { render :show, status: :created, location: @challenge }
      else
        format.html { render :new }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /challenges/1
  # PATCH/PUT /challenges/1.json
  def update
    respond_to do |format|
      if @challenge.update(challenge_params)
        format.html { redirect_to @challenge, notice: 'Challenge was successfully updated.' }
        format.json { render :show, status: :ok, location: @challenge }
      else
        format.html { render :edit }
        format.json { render json: @challenge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /challenges/1
  # DELETE /challenges/1.json
  def destroy
    @challenge.destroy
    respond_to do |format|
      format.html { redirect_to challenges_url, notice: 'Challenge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_challenge
      @challenge = Challenge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def challenge_params
      params.require(:challenge).permit(:title, :body, :prize, :company)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def home 
  end 	

  def learn
  end
  
end 

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password, :birthday, :country, :state, :school, :gender, :phone_number, :field, :job_role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :update, :destroy]   

  def index
    @users = User.all
  end

  def edit 
  end   

  def show
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

  private

  def set_user 
    @user = User.find(params[:id])
  end   

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index 
  	@challenges = Challenge.all
  end 	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/challenges_helper.rb
module ChallengesHelper
end

app/views/challenges/_form.html.erb
<%= form_for(@challenge) do |f| %>
  <% if @challenge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@challenge.errors.count, "error") %> prohibited this challenge from being saved:</h2>

      <ul>
      <% @challenge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :body %>
    <%= f.text_area :body %><br>
    <%= f.label :company %>
    <%= f.text_field :company %><br>
    <%= f.label :prize %>
    <%= f.number_field :prize %><br>
    <%= f.submit %>
  </div>
<% end %>

app/views/challenges/edit.html.erb
<h1>Editing Challenge</h1>

<%= render 'form' %>

<%= link_to 'Show', @challenge %> |
<%= link_to 'Back', challenges_path %>

app/views/challenges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Challenges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @challenges.each do |challenge| %>
      <tr>
        <td><%= link_to 'Show', challenge %></td>
        <td><%= link_to 'Edit', edit_challenge_path(challenge) %></td>
        <td><%= link_to 'Destroy', challenge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Challenge', new_challenge_path %>

app/views/challenges/new.html.erb
<h1>New Challenge</h1>

<%= render 'form' %>

<%= link_to 'Back', challenges_path %>

app/views/challenges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_challenge_path(@challenge) %> |
<%= link_to 'Back', challenges_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to current_user.name, user_path(current_user)  %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-fixed-top bg-faded">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DataScience', root_path, class: 'navbar-brand' %>
    </div>
    <div class="nav-list collapse navbar-collapse float-right">
      <ul class="nav navbar-nav">
        <li><a href="/challenge">Challenges</a></li>
        <li><a href="/learn"> Learn </a></li>
        <li><a href=""> Community </a></li>
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div>
       <%= yield %>
    </div>   
  </body>
</html>

app/views/pages/about.html.erb
<style>
        #header{background:black;}
        #header h1 {color:forestgreen; font-weight:bolder;padding-top:120px; font-family:"Fascinate Inline"; font-size:56px;}
        i{color:forestgreen;font-size:80px;font-weight:bolder;}
        h4{text-align:center; font-size:16px; font-family:gothic;font-weight:bolder;color:black;}
        .pad-bottom{padding-top:60px;padding-bottom:30px;font-family:"Inconsolata";}
        .pad-bottom p{font-weight:800; font-size:18px; font-family:gothic; }
        #testimonial {
    background: url(https://i.ytimg.com/vi/Hb_PDJ1poBg/maxresdefault.jpg) no-repeat center center;
    padding: 0;
    -webkit-background-size: cover;
    background-size: cover;
    -moz-background-size: cover;
    background-attachment: fixed;
}

    #testimonial .overlay {
        background-color: rgba(0,0,0,0.7);
        padding-top: 40px;
        min-height: 300px;
        color: #fff;
        padding-top: 100px;
        padding-bottom: 100px;
    }
    </style>
<div id="header" >
            <div class="container">
                <div class="row">
                    <div class="col-md-12 text-center ">
                        <h1>ABOUT DATASCIENCE.NG</h1>
                    </div>
                </div>
            </div>

    </div>
    <!--HEADER SECTION END  -->
    <section id="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-6 col-md-offset-3 pad-bottom" data-scroll-reveal="enter from the bottom after 0.2s">
                    <h2><strong>OUR FOCUS AREAS</strong></h2>
                    <p>
                        Our main focus area for training and support are inline with the current skill demand around nationwide data and information management.</p>

                </div>
            </div>
            <div class="row text-center pad-bottom" data-scroll-reveal="enter from the bottom after 0.4s">
                <div class="col-md-3">
                    <i class="ion-chatbubbles"></i>
                    <h4><strong>DATA COLLECTION </strong></h4>
                   
                </div>
                <div class="col-md-3">
                    <i class="ion-ios-list"></i>
                    <h4><strong>DATA ENTRY & STORAGE</strong></h4>
                    
                </div>
                <div class="col-md-3">
                    <i class="ion-soup-can-outline"></i>
                    <h4><strong>DATABASE ADMINISTRATORS</strong></h4>
                   
                </div>
                <div class="col-md-3">
                    <i class="ion-ios-pie-outline"></i>
                    <h4><strong>DATA ANALYSTS</strong></h4>
                    
                </div>
            </div>
            <div class="row text-center" data-scroll-reveal="enter from the bottom after 0.6s">
                <div class="col-md-3">
                    <i class="ion-ios-flask"></i>
                    <h4><strong>DATA SCIENTISTS</strong></h4>
                    
                </div>
                <div class="col-md-3">
                    <i class="ion-code-working"></i>
                    <h4><strong>BIG DATA EXPERTS</strong></h4>
                    
                </div>
                <div class="col-md-3">
                    <i class="ion-settings"></i>
                    <h4><strong>DATA ENGINEERS</strong></h4>
                   
                </div>
                <div class="col-md-3">
                    <i class="ion-monitor"></i>
                    <h4><strong>DATA HARDWARE HACKERS</strong></h4>
                    
                </div>
            </div>
        </div>


    </section>
    
    <div class="container-fluid apply" style="background:lightgreen; height:150px;">
        <p style="text-align:center; font-weight:bolder; font-family:gothic; font-size:40px;padding:50px;color:black;">WE SIMPLY LEARN BY DOING.<a href="#"><i class="ion-ios-play" style="font-size:40px;padding:50px;color:black;"></i></a></p>
    </div>
    
    <div id="testimonial">
        <div class="overlay">
            <div class="container">
                <div class="row text-center">
                    <div class="col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4">
                        <i class="ion-ios-drag clr-set f-big"></i>
                        <br />
                        
                   <p>Datascience.ng is on a mission to bridge the gap between education, theory & industry. Our goal is to ensure skills are developed to meet societal business and innovation needs. </p>
                   
                   <p>We scout, nuture, train and prepare the next generation data experts.</p>

                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/pages/challenges.html.erb
<div class="container-fluid" style="margin-top:40px">
         <div class= "container-fluid">
        <h3>APPLY FOR A COMPETITION HERE <a href="apply.html"><i class="fa fa-caret-right"></i></a></h3>
        
    </div>
         
         
         <!--THIS IS THE PANELS FOR THE COMPETITIONS PAGE-->
          <section id="about-us">
       		
			<!-- our-team -->
			<div class="team">
				<div class="row clearfix">
					<div class="col-md-4 col-sm-6">	
						<div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
                                    <h4>COLLECT AND STORE AGRIC DATA ACROSS NIGERIAN STATES</h4>
                                    <ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 1</a></li>
										<li class="btn"><a href="#">DSNG</a></li>
                                   <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
                                    <p>For Each Nigerian State, Collect and Record the Following Variables.</p>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">3 Months</a></li>
										<li class="btn pull-right"><a href="#">Collector DSNG</a></li>
									</ul>
				          </div>
						</div>
					</div><!--/.col-lg-4 -->
                    </div>
					
					
					<div class="col-md-4 col-sm-6 col-md-offset-2">	
				
						<div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
									<h4>WEB APPLICATION TO ACCURATELY MONITOR KPIs FOR CAFE NEOs SALES</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 6</a></li>
										<li class="btn"><a href="#">CAFE NEO</a></li>
                                    <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
                                    <p>Cafe Neo want to improve sales performance and customer satisfaction.</p>
								</div>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">N200,000</a></li>
										<li class="btn pull-right"><a href="#">5 Months</a></li>
									</ul>
				          </div>
						</div>
					</div><!--/.col-lg-4 -->					
				</div> <!--/.row -->
				<div class="row team-bar">
					<div class="first-one-arrow hidden-xs">
						<hr>
					</div>
					<div class="first-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="second-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
					<div class="third-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="fourth-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
				</div> <!--skill_border-->       
				<div class="row clearfix">   
					<div class="col-md-4 col-sm-6 col-md-offset-2">	
						<div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media closed">
								<div class="media-body">
									<h4>SISOGLOCAL WANTS A DATABASE FOR THE IDPS</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 5</a></li>
										<li class="btn"><a href="#">SISO</a></li>
                                    <li class="btn pull-right"><i class="fa fa-toggle-off"></i></li>
                                    </ul>
                                    <p>Sisioglocal wants a simple web interface that collects data at the front end and updates database at the backend..</p>
								</div>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">N300,000</a></li>
										<li class="btn pull-right"><a href="#">2 Months</a></li>
									</ul>
				          </div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 col-md-offset-2">
						<div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
									<h4>PAYLATER'S POTENTIAL LOANERS</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 2</a></li>
										<li class="btn"><a href="#">ONEFI</a></li>
                                    <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
                                    <p>Paylater wants to identify potential customers via twitter, facebook and instagram.</p>
								</div>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">N600,000</a></li>
										<li class="btn pull-right"><a href="#">5 Months</a></li>
									</ul>
				          </div>
						</div>
					</div>
				</div>	<!--/.row-->
			</div><!--section-->
		</div><!--/.container-->
   <div class="row team-bar">
					<div class="first-one-arrow hidden-xs">
						<hr>
					</div>
					<div class="first-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="second-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
					<div class="third-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="fourth-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
				</div> <!--skill_border-->       
   	<div class="team">
				<div class="row clearfix">
					<div class="col-md-4 col-sm-6">	
						<div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
                                    <h4>ZEESAA'S DATA ANALYSIS</h4>
                                    <ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 5</a></li>
										<li class="btn"><a href="#">DSNG</a></li>
                                    <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
                                    <p> ZEESAA wants a web app to monitor suply chain logistics and improve supply chain performance.</p>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">ANALYST @ ZEESAA</a></li>
										<li class="btn pull-right"><a href="#">2 Months</a></li>
										 
									</ul>
				          </div>
						</div>
					</div><!--/.col-lg-4 -->
                    </div>
					
					
					<div class="col-md-4 col-sm-6 col-md-offset-2">	
				
						<div class="single-profile-top wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
									<h4>ONEFI WANTS A MODEL TO PREDICT CREDIT DEFAULT OF ITS POTENTIAL CUSTOMERS.</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 2</a></li>
										<li class="btn"><a href="#">ONEFI</a></li>
                                    <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
                                    
                                    <p>Onefi is a FinTech company looking to reduce risk associated with money lending and borrowing.</p>
								</div>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">DataScientist @ Onefi</a></li>
										<li class="btn pull-right"><a href="#">1 Month</a></li>
									</ul>
				          </div>
						</div>
					</div><!--/.col-lg-4 -->					
				</div> <!--/.row -->
				<div class="row team-bar">
					<div class="first-one-arrow hidden-xs">
						<hr>
					</div>
					<div class="first-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="second-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
					<div class="third-arrow hidden-xs">
						<hr> <i class="fa fa-angle-up"></i>
					</div>
					<div class="fourth-arrow hidden-xs">
						<hr> <i class="fa fa-angle-down"></i>
					</div>
				</div> <!--skill_border-->       
				<div class="row clearfix">   
					<div class="col-md-4 col-sm-6 col-md-offset-2">	
						<div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
									<h4>INTEGRATE NEWS ARTICLES AND CRISIS DATA TO PREDICT THE NEXT BH CRISIS</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 5</a></li>
										<li class="btn"><a href="#">DSNG</a></li>
                                   <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
									<p>Integrating Social Media Data With crisis data, Find correlations across Variables and Time Patterns.</p>
								</div>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">PRACTICE</a></li>
										<li class="btn pull-right"><a href="#">1 Month</a></li>
										
										
									</ul>
				          </div>
						</div>
					</div>
					<div class="col-md-4 col-sm-6 col-md-offset-2">
						<div class="single-profile-bottom wow fadeInUp" data-wow-duration="1000ms" data-wow-delay="300ms">
							<div class="media open">
								<div class="media-body">
									<h4>CLUSTER NIGERIAN STATES FOR EFFECTIVE POLICY ADMINISTRATION</h4>
									<ul class="tag clearfix">
										<li class="btn pull-left"><a href="#">LEVEL 2</a></li>
										<li class="btn"><a href="#">DSNG</a></li>
                                   <li class="btn pull-right"><i class="fa fa-toggle-on"></i></li>
                                    </ul>
								</div>
								<p>Using data collected o Nigerian States perform a cluster analysis of all states without Bias.</p>
							</div><!--/.media -->
							
							<div class="media-body">
									<ul class="tag clearfix">
										<li class="btn pull-right"><a href="#">PRACTICE</a></li>
										<li class="btn pull-right"><a href="#">1 wEEK</a></li>
										
									</ul>
				          </div>
						</div>
					</div>
				</div>	<!--/.row-->
			</div><!--section-->
		</div><!--/.container-->
    </section><!--/about-us-->
    <!--THIS IS THE PANELS FOR THE COMPETITIONS PAGE ENDS HERE-->
    
    <div class= "container-fluid">
        <h3>APPLY FOR A COMPETITION HERE <a href="apply.html"><i class="fa fa-caret-right"></i></a></h3>
        
    </div>
    
    
    
    
    </div>

app/views/users/_form.html.erb
<%= form_for [@user, @user.profile.build] do |f| %>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :date_of_birth %><br>
    <%= f.date_select :date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :home_address %><br>
    <%= f.text_field :home_address %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :phone_number2 %><br>
    <%= f.text_field :phone_number2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<div class="col-md-12 bg-container">
	<div class="row">
		<div class="bg-image">
	    </div>
    </div>
</div>    
<div id="landing-text" class="col-md-12">
	<h1>A Team Of Data Scientists Is At Your Fingertips</h1>
	<p>For data enthusiast, learn the skills required to make data driven business decisions.</p>
</div>
<div id="recent-challenges" class="col-md-12">
	<div class="rc-header"><p>Recent Challenge</p>
		<h1>hello</h1>
	</div>
	<% @challenges.each do |c| %>
	<div class="panel panel-info challenge-box">
		<div class="panel-header">
			<%= c.title %>
		</div>
		<div class="panel-body">
			<%= c.body %>
		</div>
		<div class="panel-footer">
			<%= c.prize %>
		</div>
	</div>

	<% end %>

</div>